"""Lunar tiling, chip creation, and supporting geospatial utilities."""

from .chip_config import (
    AcquisitionGroupConfig,
    ChipConfig,
    MixedPercentageNumberSplitConfig,
    NumberSplitConfig,
    OutputModalityConfig,
    SimpleSplitConfig,
    SplitConfig,
    SplitConfigType,
    SplitCounts,
    SplitName,
    SplitPercentages,
    chip_config_from_dict,
    default_split_config,
    default_zoom_for_sources,
    split_config_from_dict,
)
from .chip_types import (
    ChipPreflight,
    ChipRequest,
    ChipResult,
    GeographicAOI,
    LabelMismatchError,
    LabelValidationDiagnostic,
    ReferenceSample,
    SourceSelector,
    TargetGrid,
    validate_request_contracts,
)
from .chip_labels import preflight_label, resolve_label_path, validate_label
from .chip_preflight import (
    BatchPreflightResult,
    PreparedChipRequest,
    preflight_chip_requests,
)
from .chip_requests import (
    AmbiguousLongitudeError,
    UnsupportedCoverageError,
    chip_request_from_aoi,
    chip_request_from_reference,
    chip_requests_from_reference_directory,
    chip_requests_from_reference_paths,
    discover_reference_tiffs,
    geographic_aoi_from_target_grid,
    geographic_query_parts,
    materialize_requests,
    normalize_sample_id,
    product_id_from_sample_id,
    reference_sample_from_tiff,
    target_grid_from_bounds,
    validate_request_geographic_aoi,
    validate_target_grid_consistency,
)
from .chip_splits import (
    SplitAssignment,
    SplitPlan,
    SplitTargetWarning,
    SplitWarning,
    plan_splits,
)
from .tiling_config import (
    BandNoDataOverride,
    TileConfig,
    TileSourceConfig,
    tile_config_from_dict,
)
from .lunar_crs import LUNAR_GEOGRAPHIC_WKT_PATH, load_lunar_geographic_wkt
from .vector_index import IndexedRaster, query_source_index
from .vector_index_builder import VectorIndexBuildConfig, create_vector_index
from .tiling_results import (
    MissingRequiredSourceError,
    TileCubeRecord,
    TileSourceError,
)
from .tiling import (
    create_tiles_for_aoi,
    create_tiles_for_index,
    create_tiles_for_point,
)
from .static_band_contract import (
    MINIRF_SOURCE_NODATA,
    MINIRF_SOURCE_NODATA_BANDS,
    STATIC_BAND_NAMES,
    STATIC_OUTPUT_NODATA,
)

__all__ = [
    "AcquisitionGroupConfig",
    "AmbiguousLongitudeError",
    "BandNoDataOverride",
    "BatchPreflightResult",
    "ChipConfig",
    "ChipPreflight",
    "ChipRequest",
    "ChipResult",
    "GeographicAOI",
    "IndexedRaster",
    "LUNAR_GEOGRAPHIC_WKT_PATH",
    "LabelMismatchError",
    "LabelValidationDiagnostic",
    "MINIRF_SOURCE_NODATA",
    "MINIRF_SOURCE_NODATA_BANDS",
    "MissingRequiredSourceError",
    "MixedPercentageNumberSplitConfig",
    "NumberSplitConfig",
    "OutputModalityConfig",
    "PreparedChipRequest",
    "ReferenceSample",
    "SimpleSplitConfig",
    "SourceSelector",
    "SplitConfig",
    "SplitConfigType",
    "SplitCounts",
    "SplitName",
    "SplitPercentages",
    "SplitAssignment",
    "SplitPlan",
    "SplitTargetWarning",
    "SplitWarning",
    "STATIC_BAND_NAMES",
    "STATIC_OUTPUT_NODATA",
    "TargetGrid",
    "TileConfig",
    "TileCubeRecord",
    "TileSourceError",
    "TileSourceConfig",
    "VectorIndexBuildConfig",
    "UnsupportedCoverageError",
    "chip_config_from_dict",
    "chip_request_from_aoi",
    "chip_request_from_reference",
    "chip_requests_from_reference_directory",
    "chip_requests_from_reference_paths",
    "create_vector_index",
    "create_tiles_for_aoi",
    "create_tiles_for_index",
    "create_tiles_for_point",
    "default_split_config",
    "default_zoom_for_sources",
    "discover_reference_tiffs",
    "geographic_aoi_from_target_grid",
    "geographic_query_parts",
    "load_lunar_geographic_wkt",
    "materialize_requests",
    "normalize_sample_id",
    "plan_splits",
    "preflight_chip_requests",
    "preflight_label",
    "product_id_from_sample_id",
    "query_source_index",
    "reference_sample_from_tiff",
    "resolve_label_path",
    "split_config_from_dict",
    "tile_config_from_dict",
    "target_grid_from_bounds",
    "validate_label",
    "validate_request_contracts",
    "validate_request_geographic_aoi",
    "validate_target_grid_consistency",
]
