"""Public tiling APIs for lunar data processing."""

from .tiling_config import (
    BandNoDataOverride,
    TileConfig,
    TileSourceConfig,
    tile_config_from_dict,
)
from .product_ids import (
    ProductIdResolutionError,
    ProductIdResolver,
    lunar_product_id_from_raster_path,
)
from .product_tiling import (
    MissingRequiredProductError,
    create_tiles_for_aoi_by_product,
    discover_products_for_aoi,
)
from .source_modes import compose_tile_sources
from .static_source import make_static_source
from .tiling_workflow import (
    AutomaticTilingError,
    ModalityPreset,
    NAC_DEFAULT_ZOOMS,
    ProductAOIWarning,
    ProductRequest,
    SourceRole,
    TileAOIQuery,
    TilePointQuery,
    TileQuery,
    TileSourceDefinition,
    create_tiles_for_query,
    default_zoom_for_modality,
    make_nac_tile_source,
    make_static_tile_source,
    make_wac_tile_source,
    resolve_tile_index_path,
    WAC_DEFAULT_ZOOMS,
)
from .grid_registry import (
    GeographicCoverage,
    GridDefinition,
    GridFamily,
    GridRegistry,
    TileMatrixDefinition,
    default_grid_registry,
    load_grid_definition,
)
from .grid_router import (
    GeographicRoutingError,
    GridPointRoute,
    GridQueryPart,
    POLAR_LATITUDE_THRESHOLD,
    normalize_lunar_longitude,
    route_aoi,
    route_point,
)
from .tiling_preparation import (
    TilePreparationResult,
    TileSourcePreparation,
    prepare_tile_config,
)
from .lunar_crs import LUNAR_GEOGRAPHIC_WKT_PATH, load_lunar_geographic_wkt
from .vector_index import (
    IndexedRaster,
    query_source_index,
    query_source_index_envelopes,
)
from .vector_index_builder import (
    DEFAULT_RASTER_GLOBS,
    StaleVectorIndexError,
    VectorIndexBuildConfig,
    VectorIndexLockError,
    VectorIndexValidationError,
    VectorIndexValidationResult,
    create_vector_index,
    discover_raster_paths,
    ensure_vector_index,
    resolve_index_worker_count,
    validate_vector_index,
)
from .notebook_indexes import (
    DEFAULT_PROJECT_DATA_DIR,
    DEFAULT_SHARED_INDEX_NAME,
    DEFAULT_SOURCE_DATA_DIRS,
    NotebookIndexResolution,
    resolve_notebook_source_index,
)
from .tiling_results import (
    MissingRequiredSourceError,
    TileCubeRecord,
    TileSourceError,
)
from .tiling import (
    create_tiles_for_aoi,
    create_tiles_for_index,
    create_tiles_for_point,
)
from .static_band_contract import (
    MINIRF_SOURCE_NODATA,
    MINIRF_SOURCE_NODATA_BANDS,
    STATIC_BAND_NAMES,
    STATIC_OUTPUT_NODATA,
)
from .wac_band_contract import (
    WAC_BAND_NAMES,
    WAC_UV_BAND_NAMES,
    WAC_VIS_BAND_NAMES,
)

__all__ = [
    "AutomaticTilingError",
    "BandNoDataOverride",
    "DEFAULT_PROJECT_DATA_DIR",
    "DEFAULT_RASTER_GLOBS",
    "DEFAULT_SHARED_INDEX_NAME",
    "DEFAULT_SOURCE_DATA_DIRS",
    "GeographicCoverage",
    "GeographicRoutingError",
    "GridDefinition",
    "GridFamily",
    "GridPointRoute",
    "GridQueryPart",
    "GridRegistry",
    "IndexedRaster",
    "LUNAR_GEOGRAPHIC_WKT_PATH",
    "MINIRF_SOURCE_NODATA",
    "MINIRF_SOURCE_NODATA_BANDS",
    "MissingRequiredProductError",
    "MissingRequiredSourceError",
    "ModalityPreset",
    "NAC_DEFAULT_ZOOMS",
    "NotebookIndexResolution",
    "POLAR_LATITUDE_THRESHOLD",
    "ProductAOIWarning",
    "ProductIdResolutionError",
    "ProductIdResolver",
    "ProductRequest",
    "STATIC_BAND_NAMES",
    "STATIC_OUTPUT_NODATA",
    "SourceRole",
    "StaleVectorIndexError",
    "TileAOIQuery",
    "TileConfig",
    "TileCubeRecord",
    "TileMatrixDefinition",
    "TilePointQuery",
    "TilePreparationResult",
    "TileQuery",
    "TileSourceConfig",
    "TileSourceDefinition",
    "TileSourceError",
    "TileSourcePreparation",
    "VectorIndexBuildConfig",
    "VectorIndexLockError",
    "VectorIndexValidationError",
    "VectorIndexValidationResult",
    "WAC_BAND_NAMES",
    "WAC_DEFAULT_ZOOMS",
    "WAC_UV_BAND_NAMES",
    "WAC_VIS_BAND_NAMES",
    "compose_tile_sources",
    "create_tiles_for_aoi",
    "create_tiles_for_aoi_by_product",
    "create_tiles_for_index",
    "create_tiles_for_point",
    "create_tiles_for_query",
    "create_vector_index",
    "default_grid_registry",
    "default_zoom_for_modality",
    "discover_products_for_aoi",
    "discover_raster_paths",
    "ensure_vector_index",
    "load_grid_definition",
    "load_lunar_geographic_wkt",
    "lunar_product_id_from_raster_path",
    "make_nac_tile_source",
    "make_static_tile_source",
    "make_static_source",
    "make_wac_tile_source",
    "normalize_lunar_longitude",
    "prepare_tile_config",
    "query_source_index",
    "query_source_index_envelopes",
    "resolve_index_worker_count",
    "resolve_notebook_source_index",
    "resolve_tile_index_path",
    "route_aoi",
    "route_point",
    "tile_config_from_dict",
    "validate_vector_index",
]
